export const JSON_API_PRODUCTS = 'http://localhost:8000/products';

export const ACTIONS = {
<<<<<<< HEAD
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
=======
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
>>>>>>> a88a44147a481a229deb930536db5e64443d2acb
};
